### ISSUE TITLE
Purpose of the project.

### ISSUE THREAD

**Issue by m-kru** [jeremiah-c-leary/design-explorer#14]
What is the purpose of this project? Do you plan to make a graphical program to explore the design, hierarchy etc. of a HDL projects?

**Comment by jeremiah-c-leary** [comment]
Hey m-kru,
Sorry, I just saw this issue.  I am currently working on some detailed documentation.

I did update the README though to provide an overview of what I am attempting to do.
Let me know what you think.

Regards,

--Jeremy
